SYSTEM_NAME="bbk"
SYSTEM_FULLNAME="BBK 4980"
SYSTEM_MANUFACTURER="BBK"
SYSTEM_RELEASE="2002"
SYSTEM_HARDWARE="electronic dictionary"
SYSTEM_PATH="/storage/roms/bbk"
SYSTEM_EXTENSION=".bin .BIN .gam"
SYSTEM_PLATFORM="bbk"
SYSTEM_THEME="bbk"
SYSTEM_WIKI_PATH="bbk"