SYSTEM_NAME="ebook"
SYSTEM_FULLNAME="EBook"
SYSTEM_MANUFACTURER="Various"
SYSTEM_RELEASE="1990"
SYSTEM_HARDWARE="EBook"
SYSTEM_PATH="/storage/roms/ebook"
SYSTEM_EXTENSION=".pdf .epub .txt"
SYSTEM_PLATFORM="ebook"
SYSTEM_THEME="ebook"
SYSTEM_WIKI_PATH="ebook"
