SYSTEM_NAME="eka2l1"
SYSTEM_FULLNAME="eka2l1"
SYSTEM_MANUFACTURER="Nokia"
SYSTEM_RELEASE="2000"
SYSTEM_HARDWARE="Nokia Mobile"
SYSTEM_PATH="/storage/.config/eka2l1/scripts/"
SYSTEM_EXTENSION=".sh"
SYSTEM_PLATFORM="Mobile phone"
SYSTEM_THEME="eka2l1"
