SYSTEM_NAME="flash"
SYSTEM_FULLNAME="Adobe Flash"
SYSTEM_MANUFACTURER="Adobe"
SYSTEM_RELEASE="1996"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/flash"
SYSTEM_EXTENSION=".swf .SWF"
SYSTEM_PLATFORM="pc"
SYSTEM_THEME="flash"
SYSTEM_WIKI_PATH="flash"
