SYSTEM_NAME="krkr2"
SYSTEM_FULLNAME="Kirikiri2"
SYSTEM_MANUFACTURER="Various"
SYSTEM_RELEASE="2000"
SYSTEM_HARDWARE="visual novel engine"
SYSTEM_PATH="/storage/roms/krkr2"
SYSTEM_EXTENSION=".kr2 .KR2"
SYSTEM_PLATFORM="krkr2"
SYSTEM_THEME="krkr2"
