SYSTEM_NAME="mkxp-z"
SYSTEM_FULLNAME="RPG Maker XP"
SYSTEM_MANUFACTURER="RPG Maker XP"
SYSTEM_RELEASE="2000"
SYSTEM_HARDWARE="RPG Maker XP"
SYSTEM_PATH="/storage/roms/mkxp"
SYSTEM_EXTENSION=".ini"
SYSTEM_PLATFORM="mkxp-x"
SYSTEM_THEME="mkxp-z"
