SYSTEM_NAME="mrp"
SYSTEM_FULLNAME="MRP"
SYSTEM_MANUFACTURER="SKY-mobi"
SYSTEM_RELEASE="2004"
SYSTEM_HARDWARE="MTK Mobile Phone"
SYSTEM_PATH="/storage/roms/mrp"
SYSTEM_EXTENSION=".mrp"
SYSTEM_PLATFORM="mrp"
SYSTEM_THEME="mrp"
