SYSTEM_NAME="native32emu"
SYSTEM_FULLNAME="native32emu"
SYSTEM_MANUFACTURER="native32emu"
SYSTEM_RELEASE="2005"
SYSTEM_HARDWARE="electronic dictionary"
SYSTEM_PATH="/storage/roms/native32emu"
SYSTEM_EXTENSION=".smf .sgm .ssl .zip"
SYSTEM_PLATFORM="native32emu"
SYSTEM_THEME="native32emu"
SYSTEM_WIKI_PATH="native32emu"