SYSTEM_NAME="onscripter"
SYSTEM_FULLNAME="ONScripter"
SYSTEM_MANUFACTURER="Various"
SYSTEM_RELEASE="2000"
SYSTEM_HARDWARE="visual novel engine"
SYSTEM_PATH="/storage/roms/onscripter"
SYSTEM_EXTENSION=".ons"
SYSTEM_PLATFORM="onscripter"
SYSTEM_THEME="onscripter"
SYSTEM_WIKI_PATH="onscripter"
