SYSTEM_NAME="varcade"
SYSTEM_FULLNAME="Vertical Arcade"
SYSTEM_MANUFACTURER="Arcade"
SYSTEM_RELEASE="0000"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/varcade"
SYSTEM_EXTENSION=".zip .7z"
SYSTEM_PLATFORM="varcade"
SYSTEM_THEME="varcade"
