LABEL ROCKNIX
  LINUX /KERNEL
  FDTDIR /
  FDT /my.dtb
  FDTOVERLAYS /overlays/mipi-panel.dtbo
  APPEND boot=${partition_boot} disk=${partition_storage} quiet console=ttyS1,1500000 console=tty0 systemd.debug_shell=ttyS1 uboot.hwid_adc=${hwid_adc}
