# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)
#
# Prefer the custom HDMI profile on AML-AUGESOUND cards.

monitor.alsa.rules = [
  {
    matches = [
      { alsa.card_name = "AML-AUGESOUND" }
    ]
    actions = {
      update-props = {
        device.profile = "output:hdmi-stereo"
      }
    }
  }
]
